name: Test CoastSat

on:
  push:
    branches:
      - github-actions  # Trigger the workflow on push events to the 'github-actions' branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests to the 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The workflow runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up Python environment
      with:
        python-version: '3.8'  # Specifies the Python version to use

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2  # Installs Miniconda to manage the Conda environment
      with:
        activate-environment: coastsat-env  # Activates the 'coastsat-env' environment
        python-version: 3.8  # Ensures Python version in the Conda environment matches the project's Python version

    - name: Create CoastSat environment
      run: |
        conda install -c conda-forge geopandas -y  # Installs geopandas using Conda
        conda install -c conda-forge earthengine-api scikit-image matplotlib astropy notebook -y  # Installs additional dependencies
        pip install pyqt5 imageio-ffmpeg  # Installs PyQt5 and imageio-ffmpeg using pip

    - name: Run Jupyter Notebook as test
      run: |
        conda activate coastsat-env  # Activates the 'coastsat-env' environment
        jupyter nbconvert --to notebook --execute example_jupyter.ipynb  # Executes the example Jupyter Notebook to ensure it runs successfully
