name: Test CoastSat

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # You can specify the latest stable version of Python here

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: coastsat-env
        python-version: 3.11  # Match the Python version in Conda environment

    - name: Initialize Conda
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda activate coastsat-env
        conda install -c conda-forge geopandas -y
        conda install -c conda-forge earthengine-api scikit-image matplotlib astropy notebook -y
        pip install pyqt5 imageio-ffmpeg

    - name: Run Jupyter Notebook as test
      run: |
        conda activate coastsat-env
        jupyter nbconvert --to notebook --execute example_jupyter.ipynb
